utils::globalVariables(
  c(
    ".keyword_synonyms",
	".keywords_control",
	".keywords_object",
	".tbl_control",
	".tbl_doi",
	".tbl_global",
	".tbl_keywords",
	".tbl_locations",
	".tbl_object",
    ".tbl_score",
	".tbl_synonyms",
	".tbl_time",
	".time_control",
	".time_object",
    "batch_keywords",
	"batch_time",
	"countries",
	"globaltrends_db",
	"location",
	"type"
  )
)