utils::globalVariables(
  c(
    ".keyword_synonyms",
    ".keywords_control",
    ".keywords_object",
    ".tbl_control",
    ".tbl_doi",
    ".tbl_global",
    ".tbl_keywords",
    ".tbl_locations",
    ".tbl_object",
    ".tbl_score",
    ".tbl_synonyms",
    ".tbl_time",
    ".time_control",
    ".time_object",
    "countries",
    "example_keywords",
    "example_time",
    "globaltrends_db",
    "location",
    "type"
  )
)
